version: '3'
services:
  database:
    image: postgres
    container_name: wallet_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
