server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://database:5432/wallet
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    default-schema: public
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/wallet
logging:
  level:
    io.io.ylab: DEBUG

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operations-sorter: method

swagger:
  info:
    title: "API Wallet"
    description: "Backend сервис для приложения «Wallet»"

