server:
  port: 8080
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.changelog.xml
    default-schema: public
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/wallet
logging:
  level:
    io.ylab: DEBUG

